# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  horizontrackrapi:
    image: horizontrackrapi
    build:
      context: .
      dockerfile: HorizonTrackr/backend-dotnet/HorizonTrackrAPI/Dockerfile
    ports:
      - 5166:5166
