FROM mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-1809 AS base
WORKDIR /app
EXPOSE 5166

ENV ASPNETCORE_URLS=http://+:5166

FROM mcr.microsoft.com/dotnet/sdk:9.0-nanoserver-1809 AS build
ARG configuration=Release
WORKDIR /src
COPY ["HorizonTrackr/backend-dotnet/HorizonTrackrAPI/HorizonTrackrAPI.csproj", "HorizonTrackr/backend-dotnet/HorizonTrackrAPI/"]
RUN dotnet restore "HorizonTrackr\backend-dotnet\HorizonTrackrAPI\HorizonTrackrAPI.csproj"
COPY . .
WORKDIR "/src/HorizonTrackr/backend-dotnet/HorizonTrackrAPI"
RUN dotnet build "HorizonTrackrAPI.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "HorizonTrackrAPI.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HorizonTrackrAPI.dll"]
